name: Deploy (DEV)
on:
  workflow_dispatch: 
    inputs:
      deploy_web:
        description: 'Deploy Web Server?'
        type: boolean
        default: true
      deploy_scraper:
        description: 'Deploy Scraper Job?'
        type: boolean
        default: true
      reason:
        description: 'Why are we deploying?'
        required: false
        default: 'Regular update'
  push:
    branches: [ main ]
    paths: 
      - 'backend/web-server/**'
      - 'backend/scraper/**'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Env File from Secret
        run: |
          echo "${{ secrets.BACKEND_ENV_DEV }}" > backend/env.yaml     
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      # Deploy Web Server
      - name: 'Deploy Web Server (Dev)'
        if: contains(github.event.head_commit.modified, 'backend/web-server/') || github.event_name == 'workflow_dispatch'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'backend-dev'
          region: 'europe-southwest1'
          source: './backend/web-server'
          env_vars_file: 'backend/env.yaml'
      
      # Deploy Scraper (Job)
      - name: 'Deploy Scraper Job'
        if: contains(github.event.head_commit.modified, 'backend/scraper/') || github.event_name == 'workflow_dispatch'
        run: |
          gcloud run jobs deploy scraper-job-dev \
            --source ./backend/scraper \
            --region europe-west1 \
            --env-vars-file backend/env.yaml \
            --quiet
