name: Deploy (PROD)
on:
  workflow_dispatch:
    inputs:
      deploy_web:
        description: 'Deploy Web Server?'
        type: boolean
        default: true
      deploy_scraper:
        description: 'Deploy Scraper Job?'
        type: boolean
        default: true
      reason:
        description: 'Why are we deploying?'
        required: false
        default: 'Regular update'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Env File from Secret
        run: |
          echo "${{ secrets.BACKEND_ENV_PROD }}" > backend/env.yaml     
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Copy Web Server Dockerfile'
        if: inputs.deploy_web
        run: cp backend/web-server/Dockerfile backend/Dockerfile

      # Deploy Web Server
      - name: 'Deploy Web Server (PROD)'
        if: inputs.deploy_web
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'backend-prod'
          source: './backend' # include all backend to include shared libs
          region: 'europe-southwest1' # web server is in europe-southwest1
          env_vars_file: 'backend/env.yaml'

      # Deploy Scraper (Job)
      - name: 'Deploy Scraper Job (PROD)'
        if: inputs.deploy_scraper
        run: |  # scraper is in europe-west1 
          cp backend/scraper/Dockerfile backend/Dockerfile
          gcloud run jobs deploy scraper-job-prod \
            --source ./backend \
            --region europe-west1 \
            --env-vars-file backend/env.yaml \
            --quiet
