name: Backend Deploy (DEV)
on:
  workflow_dispatch: 
    inputs:
      reason:
        description: 'Why are we deploying?'
        required: false
        default: 'Regular update'
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Env File from Secret
        run: |
          echo "${{ secrets.BACKEND_ENV_DEV }}" > backend/env.yaml     
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'hello-backend-dev'
          region: 'us-central1'
          source: './backend'
          env_vars_file: 'backend/env.yaml'